Fix master mode stars from showing in Damage Display Feature
Fix3dll/SkyblockAddons pull request #21
Opened 2024-03-04 18:52 UTC by AxleCat284

Changes the item display feature from showing 
```
Heroic Hyperion ➋
```
to
```
Heroic Hyperion 
```

Yes this works yes I've tested it, yes it compiles and yes I am currently using a 7 star hyperion dont question me

2024-03-04 23:15 UTC, Fix3dll requested changes

2024-03-06 03:02 UTC, AxleCat284 commented on src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
> +                    text = holdingItem.getDisplayName().replaceAll("§[a-f0-9]?✪|➊|➋|➌|➍|➎|➏|➐|➑|➒", "");
Obviously but I was grinding zombie 9 and I didn't want to turn on my already tired brain - I'll test and make these changes tmr

2024-03-06 23:14 UTC, AxleCat284 commented on src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
> +                    text = holdingItem.getDisplayName().replaceAll("§[a-f0-9]?✪|➊|➋|➌|➍|➎|➏|➐|➑|➒", "");
@Fix3dll alrighty, tested it with 
```java
                } else if (DamageDisplayItem.getByID(skyblockItemID) != null) {
                    text = holdingItem.getDisplayName().replaceAll("(?:§[a-f0-9]?✪|➊-➒)+", "");
                } 
 ```
and other variations and it seems that even though it works on sites like regex101, hypixel is just a tad funny and it doesn't regex away the ➋ or ➏ for example
 let me know if I've done something wrong :D

2024-03-07 11:57 UTC, Fix3dll commented on src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
> +                    text = holdingItem.getDisplayName().replaceAll("§[a-f0-9]?✪|➊|➋|➌|➍|➎|➏|➐|➑|➒", "");
@AxleCat284  Firstly `➊-➒` and `[➊-➒]` arent same. Secondly don't forget the color code `§c` for future updates.

2024-03-07 12:11 UTC, merged