Added options to display icons for several HUDs
Fix3dll/SkyblockAddons pull request #72
Opened 2024-10-27 21:39 UTC by MisterCheezeCake

Added options to display icons for the Health, Mana, Defense, and Effective Health HUD.

2024-10-27 23:16 UTC, Fix3dll requested changes
I would appreciate it if you could make these small changes.

2024-10-27 23:16 UTC, Fix3dll commented on src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
> +                text = TextUtils.formatNumber(getAttribute(Attribute.MANA)) + "/" + TextUtils.formatNumber(getAttribute(Attribute.MAX_MANA)) + (main.getConfigValues().isEnabled(Feature.MANA_TEXT_ICON
Please prefer to use `Feature.MANA_TEXT_ICON.isEnabled()`

2024-10-27 23:16 UTC, Fix3dll commented on src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
> +                if (main.getConfigValues().isEnabled(Feature.HEALTH_TEXT_ICON)) {
^ `Feature.HEALTH_TEXT_ICON.isEnabled()`

2024-10-27 23:16 UTC, Fix3dll commented on src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
> +                text = TextUtils.formatNumber(getAttribute(Attribute.DEFENCE)) + (main.getConfigValues().isEnabled(Feature.DEFENCE_TEXT_ICON) ? "❈" : "");
^

2024-10-27 23:16 UTC, Fix3dll commented on src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
> +                text = TextUtils.formatNumber(Math.round(getAttribute(Attribute.HEALTH) * (1 + getAttribute(Attribute.DEFENCE) / 100F))) + (main.getConfigValues().isEnabled(Feature.EFFECTIVE_HEALTH_T
^

2024-10-27 23:16 UTC, Fix3dll commented on src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java
> +                            "/" + TextUtils.formatNumber(getAttribute(Attribute.MAX_HEALTH)) + (main.getConfigValues().isEnabled(Feature.HEALTH_TEXT_ICON) ? "❤" : "")
^

2024-10-27 23:46 UTC, MisterCheezeCake commented
Requested changes made

2024-10-28 12:41 UTC, Fix3dll approved these changes
LGTM

2024-10-28 12:53 UTC, merged